// Expose the API documentation module.
pub mod admin;
pub mod auth;
pub mod cases;
pub mod docs;
pub mod error;

// Expose the health-check routes module.
pub mod health;
pub mod hospitals;
mod money;
pub mod patients;
pub mod payments;
pub mod tokens;

// `Router` is Axum's route collection type.
// `routing::get` is a helper for registering GET endpoints.
use std::sync::Arc;

use axum::{extract::DefaultBodyLimit, routing::get, Router};

// `PgPool` is SQLx's PostgreSQL connection pool type.
use sqlx::PgPool;

// `CorsLayer` controls which browsers/frontends can call the API.
// `TraceLayer` logs useful information about incoming HTTP requests.
use tower_http::{cors::CorsLayer, trace::TraceLayer};

// `OpenApi` gives us the `.openapi()` function generated by utoipa.
use utoipa::OpenApi;

// `SwaggerUi` serves browser-based API documentation.
use utoipa_swagger_ui::SwaggerUi;

use crate::port::{
    auth::{PasswordHasher, TokenService},
    donation::DonationRepository,
    email::EmailService,
    hospital::HospitalRepository,
    medical_case::MedicalCaseRepository,
    patient::PatientRepository,
    patient_declaration::PatientDeclarationRepository,
    payment::PaymentGateway,
    refresh_token::RefreshTokenRepository,
    settlement::HospitalSettlementRepository,
    storage::DocumentStorage,
    sui::DonationProofPublisher,
};

// `AppState` is data shared with all Axum route handlers.
//
// `Clone` is required because Axum clones state internally when routing requests.
#[derive(Clone)]
pub struct AppState {
    // The shared PostgreSQL connection pool.
    //
    // Handlers can use this to query the database.
    pub db_pool: PgPool,

    pub hospital_repository: Arc<dyn HospitalRepository>,
    pub medical_case_repository: Arc<dyn MedicalCaseRepository>,
    pub donation_repository: Arc<dyn DonationRepository>,
    pub patient_repository: Arc<dyn PatientRepository>,
    pub patient_declaration_repository: Arc<dyn PatientDeclarationRepository>,
    pub refresh_token_repository: Arc<dyn RefreshTokenRepository>,
    pub settlement_repository: Arc<dyn HospitalSettlementRepository>,
    pub password_hasher: Arc<dyn PasswordHasher>,
    pub token_service: Arc<dyn TokenService>,
    pub payment_gateway: Arc<dyn PaymentGateway>,
    pub donation_proof_publisher: Arc<dyn DonationProofPublisher>,
    pub document_storage: Arc<dyn DocumentStorage>,
    pub email_service: Arc<dyn EmailService>,
    pub jwt_expires_in_seconds: i64,
    pub refresh_token_expires_in_seconds: i64,
    pub max_upload_bytes: usize,
    pub super_admin_email: String,
    pub super_admin_password: String,
    pub app_base_url: String,
    pub app_name: String,
    pub paystack_webhook_secret: Option<String>,
    pub paystack_transfers_enabled: bool,
    pub paystack_transfer_currency: String,
    pub paystack_transfer_source: String,
    pub sui_network: String,
}

// Build the full Axum application router.
//
// `state` is passed in from `main.rs` after the database pool is created.
pub fn app(state: AppState) -> Router {
    // Start with an empty router.
    Router::new()
        // Add Swagger UI at /docs.
        //
        // The browser UI loads the OpenAPI JSON from /api-docs/openapi.json.
        .merge(SwaggerUi::new("/docs").url("/api-docs/openapi.json", docs::ApiDoc::openapi()))
        // Register GET /health.
        .route("/health", get(health::health_check))
        // Register GET /health/db.
        .route("/health/db", get(health::database_health_check))
        .nest("/cases", cases::routes())
        .nest("/api/v1/payments", payments::routes())
        .nest("/api/v1/auth", auth::routes())
        .nest("/api/v1/admin", admin::routes())
        .nest("/api/v1/hospitals", hospitals::routes())
        .nest("/api/v1/patients", patients::routes())
        .layer(DefaultBodyLimit::max(state.max_upload_bytes))
        // Allow browser requests from any frontend origin for now.
        .layer(CorsLayer::permissive())
        // Add request/response tracing for all routes registered above.
        .layer(TraceLayer::new_for_http())
        // Attach shared application state to the router.
        .with_state(state)
}
